name: Build and Deploy
on:
  workflow_dispatch:
jobs:
  build-deploy-hosting:
    name: Hosting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Install Dependencies
        run: cd frontend && npm ci
      - name: Build
        run: npm run build:frontend
      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MEDICOVER_SLOTS_NOTIFIER }}

  build-deploy-functions:
    name: Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: functions/package-lock.json
      - name: Install Dependencies
        run: cd functions && npm ci
      - name: Build
        run: npm run build:functions
      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MEDICOVER_SLOTS_NOTIFIER }}
          CONFIG_VALUES: >
            medicover.password=${{ secrets.MEDICOVER_PASSWORD }}
            medicover.username=${{ secrets.MEDICOVER_USERNAME }}
            mail.password=${{ secrets.MAIL_PASSWORD }}
            mail.host=${{ secrets.MAIL_HOST }}
            mail.user=${{ secrets.MAIL_USER }}
            mail.port=${{ secrets.MAIL_PORT }}
